name: Check Arduino

on:
  push:
    branches: [ master, test ]
  pull_request: 
    branches: [ master, test ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v1.0.0
        with:
          #path: 
          #version: 
          compliance: strict
          library-manager: update
          project-type: all
          recursive: true
          #report-file: ${{ env.REPORT_FILE_PATH }}
          #verbose: true
          #official: false
          #token: ${{ github.token }}

  compile:
    strategy:
      fail-fast: false

      matrix:
        boards: [arduino-uno, arduino-mega, arduino-leonardo]

        include:
          - boards: arduino-uno
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
            serial-enabled: true

          - boards: arduino-mega
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:mega"
            serial-enabled: true

          - boards: arduino-leonardo
            arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:leonardo"
            serial-enabled: true
    
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip Ultrasonic.zip
        run: zip -qq -r ultrasonic.zip ./src/
        working-directory: ${{ github.workspace }}

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          version: "0.19.x"

      - name: Install Arduino Platform
        run: |
          arduino-cli core download ${{ matrix.arduino-platform }}
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      
      #This is needed because we are using --zip-path to install a library
      - name: Enables unsafe install 
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true

      - name: Install Ultrasonic.h
        run: arduino-cli lib install --zip-path ./ultrasonic.zip
    